version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Stealth-Writer-Telegram-Bot"
s3_bucket = "hdduytran-deploy-bucket"
s3_prefix = "hdduytran-deploy-bucket"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
