AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Steath Writer Bot

Globals:
  Function:
    Timeout: 90
    MemorySize: 128
    Runtime: python3.10
    Tags:
      project: "Stealth Writer Bot"
    Architectures:
      - arm64
    LoggingConfig:
      LogGroup: !Sub /aws/lambda/${AWS::StackName}
      LogFormat: JSON

Resources:
  PTBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ptb/
      Handler: ptb_lambda.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE
      Role: arn:aws:iam::891377350689:role/Lambda_role
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://developer:Developer1@humanizer.d8w9rx9.mongodb.net/
          BOT_TOKEN: "7159306122:AAFnQpxlCQnwkd2Wjeo8TLzgAd1zHQl_yY0"
          INTERVAL_TIME: "300"
          TOKEN_LAMBDA: arn:aws:lambda:us-west-2:891377350689:function:Stealth-Writer-Telegram-B-StealthWriterAuthenticat-eJnouqR8hfVe

  StealthWriterAuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stealthwriter-authentication/
      Handler: lambda_handler.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE
      Role: arn:aws:iam::891377350689:role/Lambda_role
      Timeout: 300
      Environment:
        Variables:
          CAPTCHA_SECRET: 74f7ebbd661c85e251ca95336008b512
          websitekey: 5b13169c-1aa2-4267-8da1-0ebd54b6596a
          EMAIL: humanizerbot@gmail.com
          PASSWORD: "#Humanizerbot2024"
      LoggingConfig:
        LogGroup: !Sub /aws/lambda/StealthWriterAuthenticationFunction

Outputs:
  TelegramApi:
    Description: "Lambda Function URL for PTB API"
    Value:
      Fn::GetAtt: PTBFunctionUrl.FunctionUrl
