AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Steath Writer Bot

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: python3.10
    Tags:
      project: "Stealth Writer Bot"
    Architectures:
      - arm64
    LoggingConfig:
      LogGroup: !Sub /aws/lambda/${AWS::StackName}
      LogFormat: JSON

Resources:
  PTBFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ptb/
      Handler: ptb_lambda.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE
      Events:
        PTBApi:
          Type: Api 
          Properties:
            Path: /ptb
            Method: post
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://developer:Developer1@humanizer.d8w9rx9.mongodb.net/
          BOT_TOKEN: "6908330974:AAFAWDPF3DJP8ykOXTJuCpr-bWCosNcnzP8"
          INTERVAL_TIME: "300"

Outputs:
  TelegramApi:
    Description: "Lambda Function URL for PTB API"
    Value:
      Fn::GetAtt: PTBFunctionUrl.FunctionUrl
